baseURL = "https://hardcore-knuth-fc0978.netlify.com/"
languageCode = "en-us"
title = "JSON API Component Demo"

theme = ["paper","json-api"]
[outputs]
    page = ["html","json"]
    section = ["html","json"]